"""empty message

Revision ID: 2e0f61d8de83
Revises: 8a26199f2ac8
Create Date: 2024-05-02 09:40:57.177747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e0f61d8de83'
down_revision = '8a26199f2ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('team_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('team_name', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('team_description', sa.NVARCHAR(length=500), nullable=True),
    sa.Column('team_password', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('admin_id', sa.NVARCHAR(length=40), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'admin_id')
    )
    op.create_table('teamgroupss',
    sa.Column('group_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('group_title', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('author_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('color', sa.NVARCHAR(length=10), nullable=True),
    sa.Column('def_tag', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('team_id', sa.NVARCHAR(length=40), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'author_id', 'team_id')
    )
    op.create_table('teamtags',
    sa.Column('tag_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('tag_title', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('tag_color', sa.NVARCHAR(length=10), nullable=True),
    sa.Column('author_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('group_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('team_id', sa.NVARCHAR(length=40), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groupss.group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'author_id', 'group_id', 'team_id')
    )
    op.create_table('user_team',
    sa.Column('user_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('team_id', sa.NVARCHAR(length=40), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    op.create_table('teamtasks',
    sa.Column('task_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('task_title', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('task_description', sa.NVARCHAR(length=500), nullable=True),
    sa.Column('tag_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('author_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('isCompleted', sa.BOOLEAN(), nullable=True),
    sa.Column('team_id', sa.NVARCHAR(length=40), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'tag_id', 'author_id', 'team_id')
    )
    with op.batch_alter_table('groupss', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=40),
               type_=sa.NVARCHAR(length=40),
               existing_nullable=False)
        batch_op.alter_column('group_title',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=100),
               type_=sa.NVARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=40),
               type_=sa.NVARCHAR(length=40),
               existing_nullable=False)
        batch_op.alter_column('color',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=10),
               type_=sa.NVARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('def_tag',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=40),
               type_=sa.NVARCHAR(length=40),
               existing_nullable=True)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('tag_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=40),
               type_=sa.NVARCHAR(length=40),
               existing_nullable=False)
        batch_op.alter_column('tag_title',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=100),
               type_=sa.NVARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('tag_color',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=10),
               type_=sa.NVARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=40),
               type_=sa.NVARCHAR(length=40),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=40),
               type_=sa.NVARCHAR(length=40),
               existing_nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('task_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=40),
               type_=sa.NVARCHAR(length=40),
               existing_nullable=False)
        batch_op.alter_column('task_title',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=100),
               type_=sa.NVARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('task_description',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=500),
               type_=sa.NVARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('tag_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=40),
               type_=sa.NVARCHAR(length=40),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=40),
               type_=sa.NVARCHAR(length=40),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=40),
               type_=sa.NVARCHAR(length=40),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=100),
               type_=sa.NVARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=100),
               type_=sa.NVARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=256),
               type_=sa.NVARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('bio',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2000),
               type_=sa.NVARCHAR(length=2000),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=200),
               type_=sa.NVARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('image',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=200),
               type_=sa.NVARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('type_account',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=10),
               type_=sa.NVARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('external_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=40),
               type_=sa.NVARCHAR(length=40),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('external_id',
               existing_type=sa.NVARCHAR(length=40),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=40),
               existing_nullable=True)
        batch_op.alter_column('type_account',
               existing_type=sa.NVARCHAR(length=10),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=10),
               existing_nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.NVARCHAR(length=200),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=200),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.NVARCHAR(length=200),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=200),
               existing_nullable=True)
        batch_op.alter_column('bio',
               existing_type=sa.NVARCHAR(length=2000),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2000),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.NVARCHAR(length=256),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=256),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.NVARCHAR(length=100),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=100),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.NVARCHAR(length=100),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=100),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.NVARCHAR(length=40),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=40),
               existing_nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.NVARCHAR(length=40),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=40),
               existing_nullable=False)
        batch_op.alter_column('tag_id',
               existing_type=sa.NVARCHAR(length=40),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=40),
               existing_nullable=False)
        batch_op.alter_column('task_description',
               existing_type=sa.NVARCHAR(length=500),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=500),
               existing_nullable=True)
        batch_op.alter_column('task_title',
               existing_type=sa.NVARCHAR(length=100),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=100),
               existing_nullable=True)
        batch_op.alter_column('task_id',
               existing_type=sa.NVARCHAR(length=40),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=40),
               existing_nullable=False)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.NVARCHAR(length=40),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=40),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NVARCHAR(length=40),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=40),
               existing_nullable=False)
        batch_op.alter_column('tag_color',
               existing_type=sa.NVARCHAR(length=10),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=10),
               existing_nullable=True)
        batch_op.alter_column('tag_title',
               existing_type=sa.NVARCHAR(length=100),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=100),
               existing_nullable=True)
        batch_op.alter_column('tag_id',
               existing_type=sa.NVARCHAR(length=40),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=40),
               existing_nullable=False)

    with op.batch_alter_table('groupss', schema=None) as batch_op:
        batch_op.alter_column('def_tag',
               existing_type=sa.NVARCHAR(length=40),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=40),
               existing_nullable=True)
        batch_op.alter_column('color',
               existing_type=sa.NVARCHAR(length=10),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=10),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.NVARCHAR(length=40),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=40),
               existing_nullable=False)
        batch_op.alter_column('group_title',
               existing_type=sa.NVARCHAR(length=100),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=100),
               existing_nullable=True)
        batch_op.alter_column('group_id',
               existing_type=sa.NVARCHAR(length=40),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=40),
               existing_nullable=False)

    op.drop_table('teamtasks')
    op.drop_table('user_team')
    op.drop_table('teamtags')
    op.drop_table('teamgroupss')
    op.drop_table('teams')
    # ### end Alembic commands ###
