"""empty message

Revision ID: 5013cb3c8aa3
Revises: 
Create Date: 2024-05-06 18:13:05.434409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5013cb3c8aa3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('email', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('password', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('name', sa.NVARCHAR(length=256), nullable=True),
    sa.Column('bio', sa.NVARCHAR(length=2000), nullable=True),
    sa.Column('country', sa.NVARCHAR(length=200), nullable=True),
    sa.Column('image', sa.NVARCHAR(length=200), nullable=True),
    sa.Column('type_account', sa.NVARCHAR(length=10), nullable=True),
    sa.Column('external_id', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('isFillForm', sa.BOOLEAN(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('groupss',
    sa.Column('group_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('group_title', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('user_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('color', sa.NVARCHAR(length=10), nullable=True),
    sa.Column('def_tag', sa.NVARCHAR(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('team_name', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('team_description', sa.NVARCHAR(length=500), nullable=True),
    sa.Column('team_code', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('admin_id', sa.NVARCHAR(length=40), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'admin_id')
    )
    op.create_table('trees',
    sa.Column('tree_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('water', sa.Integer(), nullable=True),
    sa.Column('fert', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.NVARCHAR(length=40), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tree_id', 'user_id')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('tag_title', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('tag_color', sa.NVARCHAR(length=10), nullable=True),
    sa.Column('user_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('group_id', sa.NVARCHAR(length=40), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groupss.group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'user_id', 'group_id')
    )
    op.create_table('teamgroupss',
    sa.Column('group_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('group_title', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('author_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('color', sa.NVARCHAR(length=10), nullable=True),
    sa.Column('def_tag', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('team_id', sa.NVARCHAR(length=40), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'author_id', 'team_id')
    )
    op.create_table('teamtags',
    sa.Column('tag_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('tag_title', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('tag_color', sa.NVARCHAR(length=10), nullable=True),
    sa.Column('author_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('group_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('team_id', sa.NVARCHAR(length=40), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groupss.group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'author_id', 'group_id', 'team_id')
    )
    op.create_table('user_team',
    sa.Column('user_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('team_id', sa.NVARCHAR(length=40), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('task_title', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('task_description', sa.NVARCHAR(length=500), nullable=True),
    sa.Column('tag_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('user_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('isCompleted', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'tag_id', 'user_id')
    )
    op.create_table('teamtasks',
    sa.Column('task_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('task_title', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('task_description', sa.NVARCHAR(length=500), nullable=True),
    sa.Column('tag_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('author_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('isCompleted', sa.BOOLEAN(), nullable=True),
    sa.Column('team_id', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('completed_user', sa.NVARCHAR(length=40), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['completed_user'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'tag_id', 'author_id', 'team_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teamtasks')
    op.drop_table('tasks')
    op.drop_table('user_team')
    op.drop_table('teamtags')
    op.drop_table('teamgroupss')
    op.drop_table('tags')
    op.drop_table('trees')
    op.drop_table('teams')
    op.drop_table('groupss')
    op.drop_table('users')
    # ### end Alembic commands ###
